name = input("What is your name\n> ")
lastname = input("What is your last name\n> ")
age = int(input("What is your age\n> "))
placeofbirth = input("What is your place of birth\n> ")
favcolor = input("What is your favorite color\n> ")
petfirstname = input("What is your pet's name\n> ")
favfood = input("What is your favorite food\n> ")
print(f"Your name is {name}, \nyour last name is {lastname}, \nyour age is {age}, \nyou were born in {placeofbirth}, \nyour favorite color is {favcolor}, \nyour pets name is {petfirstname}\nand your favorite food is {favfood}.")